VECTOR_SPACE_BUTTON_BACKGROUND_COLOR = "#363062"
VECTOR_SPACE_BUTTON_FOREGROUND_COLOR = "white"
VECTOR_SPACE_SELECTED_BUTTON_BACKGROUND_COLOR = "#940B92"
VECTOR_SPACE_SELECTED_BUTTON_FOREGROUND_COLOR = "white"
